name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.4
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_sound: ^9.5.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.2
  logger: ^2.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.jpg
